/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiPagesRouteImport } from './routes/api/pages'
import { Route as ImportsSessionIdRouteImport } from './routes/imports/$sessionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses/$courseId/index'
import { Route as CoursesCourseIdImportRouteImport } from './routes/courses/$courseId/import'
import { Route as CoursesCourseIdPracticeRouteImport } from './routes/courses/$courseId/practice'
import { Route as CoursesCourseIdSettingsRouteImport } from './routes/courses/$courseId/settings'
import { Route as CoursesCourseIdStudyRouteImport } from './routes/courses/$courseId/study'
import { Route as CoursesCourseIdVocabularyRouteImport } from './routes/courses/$courseId/vocabulary'
import { Route as PagesPageIdVerifyRouteImport } from './routes/pages/$pageId/verify'
import { Route as ApiEntriesEntryIdAudioRouteImport } from './routes/api/entries/$entryId/audio'
import { Route as ApiPagesPageIdImageRouteImport } from './routes/api/pages/$pageId/image'
import { Route as CoursesCourseIdUnitsUnitIdIndexRouteImport } from './routes/courses/$courseId/units/$unitId/index'
import { Route as CoursesCourseIdUnitsUnitIdLearnRouteImport } from './routes/courses/$courseId/units/$unitId/learn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesRoute = ApiPagesRouteImport.update({
  id: '/api/pages',
  path: '/api/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsSessionIdRoute = ImportsSessionIdRouteImport.update({
  id: '/imports/$sessionId',
  path: '/imports/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdImportRoute = CoursesCourseIdImportRouteImport.update({
  id: '/courses/$courseId/import',
  path: '/courses/$courseId/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdPracticeRoute = CoursesCourseIdPracticeRouteImport.update({
  id: '/courses/$courseId/practice',
  path: '/courses/$courseId/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdSettingsRoute = CoursesCourseIdSettingsRouteImport.update({
  id: '/courses/$courseId/settings',
  path: '/courses/$courseId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdStudyRoute = CoursesCourseIdStudyRouteImport.update({
  id: '/courses/$courseId/study',
  path: '/courses/$courseId/study',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdVocabularyRoute =
  CoursesCourseIdVocabularyRouteImport.update({
    id: '/courses/$courseId/vocabulary',
    path: '/courses/$courseId/vocabulary',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesPageIdVerifyRoute = PagesPageIdVerifyRouteImport.update({
  id: '/pages/$pageId/verify',
  path: '/pages/$pageId/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntriesEntryIdAudioRoute = ApiEntriesEntryIdAudioRouteImport.update({
  id: '/api/entries/$entryId/audio',
  path: '/api/entries/$entryId/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesPageIdImageRoute = ApiPagesPageIdImageRouteImport.update({
  id: '/$pageId/image',
  path: '/$pageId/image',
  getParentRoute: () => ApiPagesRoute,
} as any)
const CoursesCourseIdUnitsUnitIdIndexRoute =
  CoursesCourseIdUnitsUnitIdIndexRouteImport.update({
    id: '/courses/$courseId/units/$unitId/',
    path: '/courses/$courseId/units/$unitId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseIdUnitsUnitIdLearnRoute =
  CoursesCourseIdUnitsUnitIdLearnRouteImport.update({
    id: '/courses/$courseId/units/$unitId/learn',
    path: '/courses/$courseId/units/$unitId/learn',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/imports/$sessionId': typeof ImportsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$courseId/import': typeof CoursesCourseIdImportRoute
  '/courses/$courseId/practice': typeof CoursesCourseIdPracticeRoute
  '/courses/$courseId/settings': typeof CoursesCourseIdSettingsRoute
  '/courses/$courseId/study': typeof CoursesCourseIdStudyRoute
  '/courses/$courseId/vocabulary': typeof CoursesCourseIdVocabularyRoute
  '/pages/$pageId/verify': typeof PagesPageIdVerifyRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/api/entries/$entryId/audio': typeof ApiEntriesEntryIdAudioRoute
  '/api/pages/$pageId/image': typeof ApiPagesPageIdImageRoute
  '/courses/$courseId/units/$unitId/learn': typeof CoursesCourseIdUnitsUnitIdLearnRoute
  '/courses/$courseId/units/$unitId/': typeof CoursesCourseIdUnitsUnitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/imports/$sessionId': typeof ImportsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$courseId/import': typeof CoursesCourseIdImportRoute
  '/courses/$courseId/practice': typeof CoursesCourseIdPracticeRoute
  '/courses/$courseId/settings': typeof CoursesCourseIdSettingsRoute
  '/courses/$courseId/study': typeof CoursesCourseIdStudyRoute
  '/courses/$courseId/vocabulary': typeof CoursesCourseIdVocabularyRoute
  '/pages/$pageId/verify': typeof PagesPageIdVerifyRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
  '/api/entries/$entryId/audio': typeof ApiEntriesEntryIdAudioRoute
  '/api/pages/$pageId/image': typeof ApiPagesPageIdImageRoute
  '/courses/$courseId/units/$unitId/learn': typeof CoursesCourseIdUnitsUnitIdLearnRoute
  '/courses/$courseId/units/$unitId': typeof CoursesCourseIdUnitsUnitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/imports/$sessionId': typeof ImportsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$courseId/import': typeof CoursesCourseIdImportRoute
  '/courses/$courseId/practice': typeof CoursesCourseIdPracticeRoute
  '/courses/$courseId/settings': typeof CoursesCourseIdSettingsRoute
  '/courses/$courseId/study': typeof CoursesCourseIdStudyRoute
  '/courses/$courseId/vocabulary': typeof CoursesCourseIdVocabularyRoute
  '/pages/$pageId/verify': typeof PagesPageIdVerifyRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/api/entries/$entryId/audio': typeof ApiEntriesEntryIdAudioRoute
  '/api/pages/$pageId/image': typeof ApiPagesPageIdImageRoute
  '/courses/$courseId/units/$unitId/learn': typeof CoursesCourseIdUnitsUnitIdLearnRoute
  '/courses/$courseId/units/$unitId/': typeof CoursesCourseIdUnitsUnitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/pages'
    | '/imports/$sessionId'
    | '/api/auth/$'
    | '/courses/$courseId/import'
    | '/courses/$courseId/practice'
    | '/courses/$courseId/settings'
    | '/courses/$courseId/study'
    | '/courses/$courseId/vocabulary'
    | '/pages/$pageId/verify'
    | '/courses/$courseId/'
    | '/api/entries/$entryId/audio'
    | '/api/pages/$pageId/image'
    | '/courses/$courseId/units/$unitId/learn'
    | '/courses/$courseId/units/$unitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/pages'
    | '/imports/$sessionId'
    | '/api/auth/$'
    | '/courses/$courseId/import'
    | '/courses/$courseId/practice'
    | '/courses/$courseId/settings'
    | '/courses/$courseId/study'
    | '/courses/$courseId/vocabulary'
    | '/pages/$pageId/verify'
    | '/courses/$courseId'
    | '/api/entries/$entryId/audio'
    | '/api/pages/$pageId/image'
    | '/courses/$courseId/units/$unitId/learn'
    | '/courses/$courseId/units/$unitId'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/pages'
    | '/imports/$sessionId'
    | '/api/auth/$'
    | '/courses/$courseId/import'
    | '/courses/$courseId/practice'
    | '/courses/$courseId/settings'
    | '/courses/$courseId/study'
    | '/courses/$courseId/vocabulary'
    | '/pages/$pageId/verify'
    | '/courses/$courseId/'
    | '/api/entries/$entryId/audio'
    | '/api/pages/$pageId/image'
    | '/courses/$courseId/units/$unitId/learn'
    | '/courses/$courseId/units/$unitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPagesRoute: typeof ApiPagesRouteWithChildren
  ImportsSessionIdRoute: typeof ImportsSessionIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CoursesCourseIdImportRoute: typeof CoursesCourseIdImportRoute
  CoursesCourseIdPracticeRoute: typeof CoursesCourseIdPracticeRoute
  CoursesCourseIdSettingsRoute: typeof CoursesCourseIdSettingsRoute
  CoursesCourseIdStudyRoute: typeof CoursesCourseIdStudyRoute
  CoursesCourseIdVocabularyRoute: typeof CoursesCourseIdVocabularyRoute
  PagesPageIdVerifyRoute: typeof PagesPageIdVerifyRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
  ApiEntriesEntryIdAudioRoute: typeof ApiEntriesEntryIdAudioRoute
  CoursesCourseIdUnitsUnitIdLearnRoute: typeof CoursesCourseIdUnitsUnitIdLearnRoute
  CoursesCourseIdUnitsUnitIdIndexRoute: typeof CoursesCourseIdUnitsUnitIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages': {
      id: '/api/pages'
      path: '/api/pages'
      fullPath: '/api/pages'
      preLoaderRoute: typeof ApiPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/$sessionId': {
      id: '/imports/$sessionId'
      path: '/imports/$sessionId'
      fullPath: '/imports/$sessionId'
      preLoaderRoute: typeof ImportsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/import': {
      id: '/courses/$courseId/import'
      path: '/courses/$courseId/import'
      fullPath: '/courses/$courseId/import'
      preLoaderRoute: typeof CoursesCourseIdImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/practice': {
      id: '/courses/$courseId/practice'
      path: '/courses/$courseId/practice'
      fullPath: '/courses/$courseId/practice'
      preLoaderRoute: typeof CoursesCourseIdPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/settings': {
      id: '/courses/$courseId/settings'
      path: '/courses/$courseId/settings'
      fullPath: '/courses/$courseId/settings'
      preLoaderRoute: typeof CoursesCourseIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/study': {
      id: '/courses/$courseId/study'
      path: '/courses/$courseId/study'
      fullPath: '/courses/$courseId/study'
      preLoaderRoute: typeof CoursesCourseIdStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/vocabulary': {
      id: '/courses/$courseId/vocabulary'
      path: '/courses/$courseId/vocabulary'
      fullPath: '/courses/$courseId/vocabulary'
      preLoaderRoute: typeof CoursesCourseIdVocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$pageId/verify': {
      id: '/pages/$pageId/verify'
      path: '/pages/$pageId/verify'
      fullPath: '/pages/$pageId/verify'
      preLoaderRoute: typeof PagesPageIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entries/$entryId/audio': {
      id: '/api/entries/$entryId/audio'
      path: '/api/entries/$entryId/audio'
      fullPath: '/api/entries/$entryId/audio'
      preLoaderRoute: typeof ApiEntriesEntryIdAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/$pageId/image': {
      id: '/api/pages/$pageId/image'
      path: '/$pageId/image'
      fullPath: '/api/pages/$pageId/image'
      preLoaderRoute: typeof ApiPagesPageIdImageRouteImport
      parentRoute: typeof ApiPagesRoute
    }
    '/courses/$courseId/units/$unitId/': {
      id: '/courses/$courseId/units/$unitId/'
      path: '/courses/$courseId/units/$unitId'
      fullPath: '/courses/$courseId/units/$unitId/'
      preLoaderRoute: typeof CoursesCourseIdUnitsUnitIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/units/$unitId/learn': {
      id: '/courses/$courseId/units/$unitId/learn'
      path: '/courses/$courseId/units/$unitId/learn'
      fullPath: '/courses/$courseId/units/$unitId/learn'
      preLoaderRoute: typeof CoursesCourseIdUnitsUnitIdLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPagesRouteChildren {
  ApiPagesPageIdImageRoute: typeof ApiPagesPageIdImageRoute
}

const ApiPagesRouteChildren: ApiPagesRouteChildren = {
  ApiPagesPageIdImageRoute: ApiPagesPageIdImageRoute,
}

const ApiPagesRouteWithChildren = ApiPagesRoute._addFileChildren(
  ApiPagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPagesRoute: ApiPagesRouteWithChildren,
  ImportsSessionIdRoute: ImportsSessionIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CoursesCourseIdImportRoute: CoursesCourseIdImportRoute,
  CoursesCourseIdPracticeRoute: CoursesCourseIdPracticeRoute,
  CoursesCourseIdSettingsRoute: CoursesCourseIdSettingsRoute,
  CoursesCourseIdStudyRoute: CoursesCourseIdStudyRoute,
  CoursesCourseIdVocabularyRoute: CoursesCourseIdVocabularyRoute,
  PagesPageIdVerifyRoute: PagesPageIdVerifyRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
  ApiEntriesEntryIdAudioRoute: ApiEntriesEntryIdAudioRoute,
  CoursesCourseIdUnitsUnitIdLearnRoute: CoursesCourseIdUnitsUnitIdLearnRoute,
  CoursesCourseIdUnitsUnitIdIndexRoute: CoursesCourseIdUnitsUnitIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
