apps:
    web:
        DATABASE_URL: ENC[AES256_GCM,data:c3p+K+eKFvxhA4RI0INUdZqWel+FK+0cT1SlDI17V7Je/NVuPAXbhGvuD5ndiwSszK3zBl25FnThSg==,iv:BKn+fRZGkjy8MF0dPvJkM8YiLD1q84IMJPyjqanP0xM=,tag:+QXMs5DHJ/rfgHiPf8fCuA==,type:str]
        AUTH_SECRET: ENC[AES256_GCM,data:QO/dA9mhqu2wqirkEXKhsWgKqzhRLtGcjolJXX0LG5jdYsj7jwZfepPsMoL9n6G/8gEsDM2YWlUuH631LQVp2w==,iv:IH9/OL4UAGj/SR3NE/2nfC3tkdQwQdp5C6wJnBP9YYk=,tag:TiO0I2kGL01pxpduOyWOYA==,type:str]
        GITHUB_CLIENT_ID: ENC[AES256_GCM,data:X4m+i9JghBvqkWvZZsIoSaMncn4=,iv:LtJvh5BoNQDX41L5VXNwytX1b8dl776bLq9n6zbO/Mw=,tag:jYMAgHgoF9ef2acQwpLySA==,type:str]
        GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:h9LnZoUHysYyB+r9uzFieYBmQsjc3i79d7XLXyOZFzzg3PFUTHfdhg==,iv:ojr1jY3zfOba6jrL0X0vPT4sqxowLNBoD8iWgV45sx4=,tag:FgDHAAFWgm048wvXKzLMOg==,type:str]
        GITHUB_ALLOWED_USER_ID: ENC[AES256_GCM,data:sdR2+Qkq6F6o,iv:77n09KzKWVuC2eIGl/6mwKaH1nseOMrX4PqYrpMz2Go=,tag:H+0bJD4F/oymTZ9epPRL+g==,type:str]
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qLfzMIJFSWCZfAhXGp6aCE2rzCs=,iv:UQtpP2MfYV89wNumJO3DfurtEJw62DyrCKYVz9CDpOE=,tag:0hB9sjAMPj32wwZfYC309w==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ILepMnDu/3EmEsxymnnrj39z/D8x611u2gIoMgxA1KxumoS2CM71KA==,iv:3kWROiGZGr9zfb/SHOvsY+JJPoX4YuSqU3DciBJN0Mc=,tag:KwZ7FnhzkzdXFiNjHwqjnQ==,type:str]
        GOOGLE_SERVICE_ACCOUNT_JSON: ENC[AES256_GCM,data:skvktDLZUugvnCnpZ9wOu7G+n7aVm7U/LIeOa0JyPUpdSTwQrvgT+cp9+tOa,iv:ckObCrzwPnRUJaHXUghecL+barqRgA3Dvhxw6Kj+C/E=,tag:bX8rrs2EkkvGbPmuEZ1sNQ==,type:str]
packages:
    db:
        DATABASE_URL: ENC[AES256_GCM,data:Z05ns2CktaZtC5jr+9Ps6sjjcenlIKIaa64faSo7+/g+omu03HCTFj8/MG4aCb8NPCfaAevQJwFL2A==,iv:hlvhqHlZMkSbsHZwb1GlUaH1Ob7mLtk4eOH5Ei7n2ng=,tag:5ssU6N/xYfVA0/jo9tPshw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T2Q4MUpaWXBPdkJsRnZL
            bEdVeUl0NFB1ZkxoTW82SWIzMmkxRzFBN0JnCkV2UkZsTE5FWmJId2g1U0FwRkRB
            bngvek56ZVVtR1k1WW5qSHdPN0ljcGMKLS0tIG1iNVVuVG80d1dERFNiVlgrMll2
            d1BqbW4zL0tXdytkc2FONWZ0RGx6RTAKaYTJNR5P2yOPcNvuIwOx/r9GlbbziyV/
            tFnfYt1mYSX+LEp0ik5YL1TdkL7el7lDN0GVsk4mLnhXEUCJ8m3dJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxzu2f027zu227f4wyf4jh5sw0w495482qfzv5flmfyjvgzxm3ys8p9muz
    lastmodified: "2026-08-26T12:09:50Z"
    mac: ENC[AES256_GCM,data:yVLiPMp7/Pi5Zkwb6CnMYeMPBmpBkkj16B71NQZ+0yVNw7t44T2LRFpMAxcEHJiH0k+DT5dV/qTwSXx3GNiOGyPMcZqLR7WAJN944sog2MJS5KXgRlRxmG2ho0JnGcpuTfycWx+ljTFkf+n0Ix0WorOGkEb3vQuBowk/XX09i/Q=,iv:XBYBhcBIyhP9KyjlRngYdzKjNDv9fZ3ZVUeunLSYqQ4=,tag:zFPtAMYCfJXd4phOilEdTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
